[project]
org-name = "ballerina"
version = "@toml.version@"

[dependencies]
"ballerina/stringutils" = "@stdlib.stringutils.version@"
"ballerina/runtime" = "@stdlib.runtime.version@"
"ballerina/time" = "@stdlib.time.version@"
"ballerina/io" = "@stdlib.io.version@"
"ballerina/log" = "@stdlib.log.version@"
"ballerina/system" = "@stdlib.system.version@"

[platform]
target = "java11"

    [[platform.libraries]]
    artifactId = "file"
    version = "@project.version@"
    path = "../file-native/build/libs/file-native-@project.version@.jar"
    groupId = "ballerina"
    modules = ["file"]

    [[platform.libraries]]
    artifactId = "org.wso2.transport.local-file-system"
    version = "6.0.55"
    path = "./lib/org.wso2.transport.local-file-system-6.0.55.jar"
    groupId = "org.wso2.transport.file"
    modules = ["file"]

    [[platform.libraries]]
    artifactId = "file"
    version = "@project.version@"
    path = "../file-test-utils/build/libs/file-test-utils-@project.version@.jar"
    groupId = "org.ballerinalang.stdlib.file"
    modules = ["file"]
    scope = "testOnly"
